version: "3.8"

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.2
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
